twig:
    file_name_pattern: '*.twig'
    paths:
      '%kernel.project_dir%/emails/css': email_css
      '%kernel.project_dir%/emails/templates': email_templates
when@test:
    twig:
        strict_variables: true
